''' This is a number guessing game between 1 & 100 and the number is choosen 
at random. The game has 2 levels
Easy : The Easy level has 10 chances
Hard level : has 5 chances
Depedning on level the user gets to guess the number, if guess right the user is winner
or the user is looser 
 
'''
import random
easy_turn =10
hard_turn =5


def nmbr_gsng_gm(num, rn,turns):
    if num < rn:
        print ("Too low")
        return (turns - 1)
    if num > rn:
        print ("Too high")
        return (turns - 1)
    elif num ==rn:
         print (f"The number is {num} and you got it")

def set_diff():
    diff=input("Choose a difficulty. Type 'easy' or 'hard':").lower()
    if diff =="easy":
       return easy_turn
    else :
        return hard_turn    

                 

def game():
    rn= random.randint(1,100)
    print("Welcome to the Number Guessing Game!\n")
    print("I am thinking a number between 1 & 100!\n")
    print(f"the random number generated by code is {rn}")
    turns= set_diff()   
    num =0
    while num != rn:
        print(f"you have {turns} left")
        num = int(input("Make a guess:"))
        turns =nmbr_gsng_gm(num,rn, turns)
        if turns ==0:
            print(f"you have used all your attempts and you loose. The number was {rn}")   
            return


    
game()
    
    #noc=0

    #for attempt in range(noc):
     #       num = int(input("Make a guess:"))
            

